### ISSUE TITLE
[material-theme] Increase font-size.

### ISSUE THREAD

**Issue by michaelcadilhac** [getnikola/nikola-themes#102]
Material is beautiful, but I believe the font-size is too small.  The theme uses 14px fonts instead of 16px, making it it slightly hard to read, while crowding the posts.  How can I increase the font-size?  Should I simply `sed -i 's/font-size: *14px/font-size: 16px/g' *css` ?

Thanks;
Cheers

**Comment by Kwpolska** [comment]
cc @matuu

**Comment by matuu** [comment]
Ok, I do it on weekend!

**Comment by Kwpolska** [comment]
I don’t think you should do this globally, documenting how to change the size if the user pleases will be better.

**Comment by michaelcadilhac** [comment]
Thanks @matuu, very appreciated!  For the record, I do agree with @Kwpolska's approach :-)

I'm not versed in CSS and these Bootstrap novelties, but I'd have been tempted to believe that all `font-size`s would have been relative to a document font-size (that is, specified in `em` for instance), so that increasing the font-size was a matter of changing a single line.  Is there a reason why it's not the case?

**Comment by matuu** [comment]
Hi @michaelcadilhac, you're right!. Simply, add `<style>body{font-size:17px;}</style>` to EXTRA_HEAD_DATA in conf.py file and ready!

I add this in README file in #107

**Comment by michaelcadilhac** [comment]
Thanks @matuu, that's perfect! Cheers!
