### ISSUE TITLE
Math rendering doesn't work with lanyon theme

### ISSUE THREAD

**Issue by tautologico** [getnikola/nikola-themes#111]
The math support mentioned in the Nikola Handbook does not work when using the lanyon theme. The LaTeX code is just wrapped in an equation* environment, and not rendered. I checked the templates and it seems the code to include the mathjax (or katex) code is not present in the theme templates.

**Comment by Kwpolska** [comment]
Cannot reproduce. Make sure…

* you added the `mathjax` tag to your post
* JavaScript is enabled
* you are using a modern browser
* you are using `nikola serve` or an otherwise real web server and not `file://`

**Comment by tautologico** [comment]
In this case I think it's a documentation bug. I looked at the docs multiple times to see if there was any additional setup to use math notation, and I didn't see any indication that I had to use the mathjax tag. Specifically, the Math section in the Handbook seems to indicate it will just work if you use .. math::. I think this section should include the indication to use the tag. 

What if I enable katex, do I still have to use the mathjax tag?

**Comment by Kwpolska** [comment]
> Nikola supports math input via MathJax. It is activated via the math roles and directives of reStructuredText and the usual LaTeX delimiters (backslash-parentheses, backslash-brackets) for other input formats.

> To use mathematics in a post, you must add the `mathjax` tag.

(From the docs)
The tag name does not depend on the renderer selected; I’ll add a note about it.

**Comment by Kwpolska** [comment]
@tautologico, please do not delete comments, especially because it’s *absolutely fine* to ask questions like this, for example if docs are not entirely clear or you otherwise have doubts.

**Comment by tautologico** [comment]
Sorry, I realized I was talking nonsense because the comment is right there in the documentation and I hadn't seen it.
