### ISSUE TITLE
[bnw] story template does not work at all

### ISSUE THREAD

**Issue by madduck** [getnikola/nikola-themes#124]
Please see https://themes.getnikola.com/v7/bnw/demo/pages/listings-demo.html for an example. Posts work, pages don't.

**Comment by Kwpolska** [comment]
@lotabout, could you take a look at this?

**Comment by lotabout** [comment]
@madduck Sorry for late response. I no longer use nikola, so the theme is not maintained any more.

Yet, the reason that listing page is not working is that `bnw` did not support it in the first place(no specific template is created).
If you are interested in hacking the theme, PRs are welcome.

**Comment by Kwpolska** [comment]
@lotabout Can we move the theme from your repo into nikola-themes (remove submodule, copy files in)? That will make maintenance easier for us.

**Comment by lotabout** [comment]
@Kwpolska Sure, please.

**Comment by Kwpolska** [comment]
Thanks! I moved the theme inside the repo and added `story.tmpl`.

Can I do the same with your lotabout theme?

**Comment by lotabout** [comment]
@Kwpolska Yes. And thank you for maintaining these themes.
