### ISSUE TITLE
[canterville] Support for mathjax

### ISSUE THREAD

**Issue by dadaromeo** [getnikola/nikola-themes#125]
Great job with the theme! It's modern, clean and cool. But it seems like it doesn't support mathjax. I think it will be a great value if there is an effort in that direction. I'm currently using it for my [blog](https://dadaromeo.github.io).

**Comment by Kwpolska** [comment]
There was a typo in the theme (also in detox and hemingway). I updated the theme, so just run `nikola theme -i canterville` to make it work again.

**Comment by ralsina** [comment]
Cool!

Feel free to change the frontpage image if that one is too generic :-D

**Comment by dadaromeo** [comment]
:+1:  It works now.
