### ISSUE TITLE
[hyde] katex css not load in home page

### ISSUE THREAD

**Issue by bebound** [getnikola/nikola-themes#126]
The `katex.min.css` will load automaticly in the post page, but not load in the home page.

So the home page did not hide the original latex expression:

<img width="693" alt="screen shot 2017-07-17 at 21 24 51" src="https://user-images.githubusercontent.com/2227874/28269961-6504a0b6-6b36-11e7-8b97-d1dabec7c1e8.png">

sample url: https://bebound.github.io

**Comment by Kwpolska** [comment]
Fixed, thanks for reporting! Please update your theme (`nikola theme -i hyde`) and rebuild.
