### ISSUE TITLE
[hyde] looks wired on small screen

### ISSUE THREAD

**Issue by bebound** [getnikola/nikola-themes#128]
url: https://bebound.github.io/posts/parameters-in-dov2vec/

It behaves different than the demo, I have no idea what the reason is. Thank you.

<img width="490" alt="screen shot 2017-08-15 at 21 09 33" src="https://user-images.githubusercontent.com/2227874/29317379-35a82f2a-81fe-11e7-8bde-152c8710ee42.png">

**Comment by Kwpolska** [comment]
The demo site behaves the same way for me. Looks like it’s how that theme is designed.
