### ISSUE TITLE
Better reference base template files 

### ISSUE THREAD

**Issue by kerstin** [getnikola/nikola-themes#131]
I'm putting this here for now because... I can't find the original reference anymore.

It'd be great if the [base template files](https://github.com/getnikola/nikola/tree/master/nikola/data/themes/base) were referenced/linked more prominently from the various pages about theming, including the lanyon tutorial.

One template must be linked from _somewhere_ because otherwise I wouldn't have known these base template files existed in the first place, but when I needed more template files, I couldn't find the original reference anymore (and ended up going through my browser history).

**Comment by Kwpolska** [comment]
The following passage appears in the lanyon tutorial:

> That file is a **template** used to generate parts of the pages. It’s large and
> complicated but we don’t need to change a lot of it. First, make a copy in your
> theme (note this command requires setting your ``THEME`` in ``conf.py`` to
> ``lanyon``):
>
>     $ nikola theme -c base_helper.tmpl

I made a few other changes to the docs (getnikola/nikola@a3dd4c2) that will appear on the website soon.
