### ISSUE TITLE
[hemingway] tags?

### ISSUE THREAD

**Issue by gnohz** [getnikola/nikola-themes#135]
I like the theme, but is there any way that I can add "tags" to it.
It is not just for navigation, but I have to use "mathjax" to show math.

**Comment by Kwpolska** [comment]
Tags don’t need to be displayed in order for  `mathjax` to work (the tag part is handled inside Nikola). If math doesn’t work, that means the theme doesn’t have math support.

@ralsina, mind looking into that?

**Comment by gnohz** [comment]
Yes, it works and displays math properly when expanding to the whole post.
It does not work only in the "teaser" status.

**Comment by Kwpolska** [comment]
I’ll look into it later.

**Comment by Kwpolska** [comment]
Fixed. The fix will be up on themes.getnikola.com in a few minutes.
