### ISSUE TITLE
[canterville] Banner image doesn't seem to work

### ISSUE THREAD

**Issue by gramster** [getnikola/nikola-themes#138]
I've tried my own and the default. I get no banner. What I do get is some text appearing when I hover near top left on site that says "Blog logo" but it links back to the top level page. 

Example at www.grahamwheeler.com

**Comment by Kwpolska** [comment]
What did you set GLOBAL_CONTEXT to? It looks like you set the banner image path to the site root instead of your desired image.

**Comment by gramster** [comment]
GLOBAL_CONTEXT = {
        'TWITTER_URL': 'https://twitter.com/gramnix',
        'GITHUB_URL': 'https://github.com/gramster',
        'LINKEDIN_URL': 'https://www.linkedin.com/in/grahamwheeler',
        'BANNER_URL': '/assets/img/IMG_5590.JPG'
        #'BANNER_URL': '/assets/img/silk_road.jpg'
    }

I have silk_road in there too because I tried it too, with exactly the same results.
