### ISSUE TITLE
[hyde] Layout is not formatted properly on mobile.

### ISSUE THREAD

**Issue by shivamvats** [getnikola/nikola-themes#139]

**Comment by tritium21** [comment]
Can you elaborate?  How is it improperly formatted?

**Comment by shivamvats** [comment]
Here is a screenshot: https://drive.google.com/file/d/1mJ_wholvZWXmUQO8ed_oPRNwdzdNX-bB/view?usp=sharing

In the Jekyll Hyde theme, the sidebar moves to the top when viewed on a mobile device.

**Comment by Kwpolska** [comment]
This issue was caused by a conflict between reST styles and Hyde (both use `.sidebar`). To fix this, I renamed Hyde’s class to `.hsidebar`. You can update the theme (`nikola theme -i hyde`) to fix this.
