### ISSUE TITLE
Some preview images are not representative of the theme

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola-themes#140]
The preview image below is rendered incorrectly, compared to how it actually renders.

![bnw](https://user-images.githubusercontent.com/1781587/34821371-7b129674-f691-11e7-9d9e-82bda76ae3ed.png)

This is how it renders in Firefox (probably correct.)

![firefox_2018-01-11_05-38-22](https://user-images.githubusercontent.com/1781587/34821492-e868adb2-f691-11e7-9d1f-a1928892dba6.png)

**Comment by ralsina** [comment]
Well, that depends on what fonts you have in the system, doesn't it?

**Comment by Kwpolska** [comment]
This is caused by PhantomJS being terribly outdated. We could fix it with headless Chrome and [Puppeteer](https://github.com/GoogleChrome/puppeteer) for example.

**Comment by tritium21** [comment]
I was more concerned with phantomjs apparently choosing to render text in arbitrarily wrong locations

**Comment by Kwpolska** [comment]
Well, that’s what I’m talking about: PhantomJS’s engine is outdated and isn’t as good at new CSS tricks as Chrome/Firefox. Font faces chosen is irrelevant.

**Comment by Kwpolska** [comment]
Fixed in commit be97dd1 by using Puppeteer. Needs one-time config and a Chrome/ium install, comes with much more accurate screenshots.
