### ISSUE TITLE
themes inaccessible via proxy server

### ISSUE THREAD

**Issue by githubgnulinux** [getnikola/nikola-themes#141]
Similar to:

https://github.com/getnikola/nikola/issues/2946

Please consider the decision to use cloudflare

**Comment by Kwpolska** [comment]
No. We’re staying with CloudFlare. Please just enter the CAPTCHA.

**Comment by felixfontein** [comment]
If anyone else has the same problem: you can also find the themes here on github, in this repository. Simply copy the theme's folder into your local Nikola theme folder (f.ex. create a subfolder `themes` in your blog's directory and copy the theme folder into there). You might need to download other theme dependencies as well.
