### ISSUE TITLE
[hpstr] Don't work correctly. CSS

### ISSUE THREAD

**Issue by Darkfoe703** [getnikola/nikola-themes#147]
Don't working correctly.
The following lines don't appereance it after the build:
```
<link href="assets/css/rst.css" rel="stylesheet" type="text/css">
<link href="assets/css/code.css" rel="stylesheet" type="text/css">
<link href="assets/css/main.css" rel="stylesheet" type="text/css">
<link href="assets/css/extra.css" rel="stylesheet" type="text/css">
```
I took the files from the example page https://themes.getnikola.com/v7/hpstr/demo/

I add this lines in index page, but when use the link of Archive, RSS, etc. the issue come back.
The problem is making these changes everytime manually.
Thank for reading. I appreciate the help.
(Sorry for the grammar, my English is so basic).
Issue's picture:
![issue](https://i.imgur.com/G5EuUOV.png)
Manual correction:
![correction](https://i.imgur.com/6N5kogo.png)

**Comment by Kwpolska** [comment]
This theme used to have no bundle support while requesting bundled assets at the same time. This has been fixed now (03c3d63, 84e34af), run `nikola theme -i hpstr` to update your copy.
