### ISSUE TITLE
[srcco.de]

### ISSUE THREAD

**Issue by augcros** [getnikola/nikola-themes#149]
Hey, this is my very first project. I just need a little assistance. I can't find anywhere in the css or directions via nikola handbook/getting started to tell me how to create pages for the "about" and the "tags". if someone could please give me a clue, i would be super appreciative.

Thanks!

**Comment by Kwpolska** [comment]
What are you referring to, and is it related to the `srcco.de` theme? Nikola creates a `/tags/` page for you by default. To create an about page, look into [creating a page](https://getnikola.com/handbook.html#creating-a-page).

PS. for questions not related to the theme, try [other support venues](https://getnikola.com/contact.html)
