### ISSUE TITLE
[hyde theme] Source code line numbers broken

### ISSUE THREAD

**Issue by hartwork** [getnikola/nikola-themes#154]
Related to #153. Source code rendering, especially the line numbers are way off with the (otherwise very appealing) hyde theme. This is recent Firefox, same in recent Chromium:

![nikola__hyde_theme__source_code](https://user-images.githubusercontent.com/1577132/40205533-aa455874-5a2c-11e8-918f-b6b695b8f810.png)

**Comment by ralsina** [comment]
The problem is that those are getting ``white-space: pre-wrap`` instead of ``pre`` so it's probably an easy fix. Looking...

**Comment by ralsina** [comment]
One line fix in def205216aab57754e0c25af05e47558ccc95680

**Comment by hartwork** [comment]
Awesome!

Now that the most off thing is fixed, i notice how the source code listing is has horizontal space at places where it doesnot add to beauty but makes the listing a lot wider than the rest of the article. I'm not suggesting to make it too short, but maybe reduce whitespace a bit and even widen the page to get them back together? Here's a picture: 

![nikola__hyde_theme__source_code_2](https://user-images.githubusercontent.com/1577132/40250110-921248ee-5ad5-11e8-905e-5b7aa9aaa697.png)

Happy to make a new ticket instead, as needed.

**Comment by ralsina** [comment]
Sure, why not.
