### ISSUE TITLE
[hyde theme] Source code listing has suboptimal spacing

### ISSUE THREAD

**Issue by hartwork** [getnikola/nikola-themes#155]
Hi!

This started os as a comment at https://github.com/getnikola/nikola-themes/issues/154#issuecomment-390284849 but here it goes as a dedicated ticket again:

Now that line number are back in line, I notice how the source code listing has horizontal space at places where it does not add to beauty but makes the listing a lot wider than the rest of the article. I'm not suggesting to make it too narrow, but maybe reduce whitespace a bit and even widen the page to get them back together? Here's a picture:

![40250110-921248ee-5ad5-11e8-905e-5b7aa9aaa697](https://user-images.githubusercontent.com/1577132/40255905-01757950-5ae9-11e8-921b-55f550d31286.png)

Thanks in advance!

**Comment by hartwork** [comment]
Hi @ralsina,

while I was very looking forward to see this in action, the numbered listing has improved a lot but unfortunately there is a regression on code listings without numbers now: No-numbers listings had some margin/padding left _and_ right for a centered look previously, but the left one is gone now which looks kind of broken:

![nikola_hyde_regression](https://user-images.githubusercontent.com/1577132/40283242-7146c890-5c7b-11e8-809f-1c0445c203ec.png)

Would be cool to have the changes only affect numbered listings again. Thanks!

**Comment by ralsina** [comment]
There is no way to do that AFAICS.

**Comment by hartwork** [comment]
Let me propose a deal: Let's revert the previous commit, re-open the bug and I try to make a pull request making both work based on your prior work. What do you think?

**Comment by ralsina** [comment]
I like it better now than before. If you want to propose a different change, please do a PR.
