### ISSUE TITLE
[material-theme]

### ISSUE THREAD

**Issue by AresScorpio** [getnikola/nikola-themes#156]
![image](https://user-images.githubusercontent.com/3578989/40274527-04b0c9c6-5bd9-11e8-94ef-0adea3f1c0e9.png)
the design seems to be broken...
i also get an error in my console:
TypeError: $(...).parent(...).colorbox is not a function

using the latest firefox

**Comment by Kwpolska** [comment]
The demo site works fine for me in both Firefox and Chrome: https://themes.getnikola.com/v8/material-theme/demo/

Does the demo site work for you? How are you testing? Any unusual browser plugins?

(The colorbox issue is expected, all themes need to be updated for Nikola v8 compatibility and this hasn’t been done yet)

**Comment by AresScorpio** [comment]
the demo site works also fine for me :astonished:  but if I apply the theme it looks like the screenshot above... i haven't changed anything just installed the theme using "nikola theme -i material-theme"
and changing my config.py (also ran a nikola clean and deleted all files manually from my server befor running nikola build and nikola deploy)

**Comment by Kwpolska** [comment]
As part of breaking-things-for-v8, we stopped shipping the unminified `bootstrap.css` file in themes. Bundles (with `USE_BUNDLES`) for this theme were broken, but they are disabled for the demo site (we used `bootstrap.min.css` in this case). Fix upcoming.

**Comment by Kwpolska** [comment]
Done, you can run `nikola theme -i material-theme` to reinstall. I also fixed colorbox warnings.

**Comment by AresScorpio** [comment]
Thank you very much!
