### ISSUE TITLE
Support custom.css in the KISS theme

### ISSUE THREAD

**Issue by ant-222** [getnikola/nikola-themes#194]
Although the official *Handbook* [claims](https://www.getnikola.com/handbook.html#customizing-your-site) universal support of `custom.css`, the `KISS` theme does not happen to respect it and thus is not customisable. I hereby request that support of `custom.css` be added to it.

**Comment by ralsina** [comment]
Hi there!

If you see the theme's README, it says it **only** works using bundles. If you want to add an extra CSS you need to add it to its bundle.

https://github.com/getnikola/nikola-themes/blob/master/v8/kiss/bundles

Just edit that file and add the CSS files you want next to the others.

**Comment by Kwpolska** [comment]
Having `custom.css` in the bundles wouldn’t hurt (we do that with `bootstrap4`). I’ll add it there.

**Comment by ant-222** [comment]
Thank you very much, @Kwpolska.

**Comment by ant-222** [comment]
@ralsina Yes, I have seen the README, but lack of `cusom.cs` supported contradicted the official *Nikola* documentation, which should take priority over the documentation of specific themes. I confirm the problem is now fixed.

**Comment by ralsina** [comment]
Honestly tempted to delete it. Blocking you.

**Comment by ant-222** [comment]
@ralsina I beg your pardon: why did you block me?
