### ISSUE TITLE
[hyde] Does Hyde theme supports generation of Twitter Cards / Open Graph data? 

### ISSUE THREAD

**Issue by kamchy** [getnikola/nikola-themes#197]
Hello, 
I  wanted to ask if hyde theme supports generation of proper title/image etc. OG tags?

I deployed generated page, but it seems twitter card cannot be generated due to insufficient markup (i.e. missing data): when I checked e.g [this blog entry] (https://kamilachyla.com/posts/java-13-i-14-bloki-tekstowe-i-rekordy/) at [twitter cards validator](https://cards-dev.twitter.com/validator) and received errors:
```
INFO:  Page fetched successfully
INFO:  8 metatags were found
INFO:  twitter:card = summary_large_image tag found
ERROR: Possibly invalid value (if specified) (twitter:title)
ERROR: Possibly invalid value (if specified) (og:title)
ERROR: Possibly invalid value (if specified) (twitter:text:title)
WARN:  this card is redirected to https://kamilachyla.com/posts/java-13-i-14-bloki-tekstowe-i-rekordy/
```

If hyde supports Twtter Cards / Open Graph data, then missing data is probably due to some kind of misconfiguration on my side.  Generated html contains  <meta> tags in <head> with content I provided in conf.py (TWITTER_CARD variable). However, no other data is generated (title, image etc).

If it does not, then perhaps  you could suggest what template(s) should I check to (possibly) try to add those missing tags? 
Thanks a lot!

**Comment by Kwpolska** [comment]
That seems to be a bug in the `hyde` theme (namely, leftover references to `use_open_graph`, which was deleted).
