### ISSUE TITLE
[srcco.de] theme not present

### ISSUE THREAD

**Issue by DO1JLR** [getnikola/nikola-themes#200]
based on https://themes.getnikola.com/v7/srcco.de/ there should be a theme at https://github.com/hjacobs/srcco.de

Well... It is not.

**Comment by Kwpolska** [comment]
If you’re looking for the theme itself, you can just install it with `nikola theme -i srcco.de`. The author moved their stuff to https://codeberg.org/hjacobs/srcco.de — I updated the link in this repo, the site will get updated someday.

**Comment by DO1JLR** [comment]
thank you. i just noticed when i started to familiarize myself with nikola and thought i'd let you know. :kissing_heart:
