### ISSUE TITLE
[hybrid] minor changes: more colour presets

### ISSUE THREAD

**Issue by encarsia** [getnikola/nikola-themes#202]
Hi there,

FTR: I've already opened a [PR](https://github.com/getnikola/nikola-themes/pull/201) on this.

I just added some more main colour options to the theme as you can see in [my blog post](https://log.bahnfreikartoffelbrei.de/posts/hybrid-theme-colours/).

I'd appreciate some feedback or your acceptance.

Regards.

**Comment by Kwpolska** [comment]
I merged the PR, it got lost in my inbox — sorry for that.
