### ISSUE TITLE
Material Theme not python3 compatible ?

### ISSUE THREAD

**Issue by mandarvaze** [getnikola/nikola-themes#64]
I get the following error when I try to use `social_links`

```
File "themes/material-theme/templates/base.tmpl", line 101, in top-level template code
{{ base.late_load_js() }}
File "themes/material-theme/templates/base_helper.tmpl", line 115, in template
{% for k,v in item.iteritems() %}


jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'iteritems'
```

When I searched for the error, I came across [this](https://github.com/mitsuhiko/jinja2/issues/150) which seems to indicate that this is python3 compatibility problem.
I fixed this (locally) by changing to `.items()` as suggested in the linked jinja2 issue.
I don't know (YET) if there is a way to support both python2 and python3, (by conditionally doing `.items` and `.iteritems()` so not sending a PR

**Comment by Kwpolska** [comment]
`.items()` is enough on both Pythons. You can send a pull request.

**Comment by Kwpolska** [comment]
(Also, please create an issue for the social buttons problem about which you left a comment on the website, and mention @matuu.)

**Comment by mandarvaze** [comment]
Done (#66) and Done (#65)

**Comment by Kwpolska** [comment]
This was fixed long ago, closing.
