### ISSUE TITLE
BNW and octopress seem to be broken

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola-themes#68]
Either it's missing some config tweak or it just doesn't work. I'll check it.

**Comment by Kwpolska** [comment]
I patched it locally once, for the list.tmpl change I think, but I haven't
sent the patch upstream. I'll do that later.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
Ah, great.

**Comment by Kwpolska** [comment]
Sent PRs to lotabout/nikola-bnw#1 and magmax/nikola-theme-octopress#4.
