### ISSUE TITLE
Latest release broke Octopress theme for github_deploy

### ISSUE THREAD

**Issue by fccoelho** [getnikola/nikola-themes#72]
I have just upgraded to nikola 7.7.5 and my Octopress theme stopped working. I am gettingo the following error:

```
[2016-02-15T19:51:52Z] INFO: github_deploy: ==> ['git', 'add', '.']
fatal: Not a git repository: themes/octopress/../../.git/modules/v7/octopress
[2016-02-15T19:51:52Z] ERROR: github_deploy: Failed GitHub deployment — command ['git', 'add', '.'] returned 128

```

**Comment by Kwpolska** [comment]
Does removing `themes/octopress/.git*` fix it?

**Comment by fccoelho** [comment]
yes it did! thanks!

On Tue, Feb 16, 2016 at 2:36 PM, Chris Warrick <notifications@github.com>
wrote:

> Does removing themes/octopress/.git* fix it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola-themes/issues/72#issuecomment-184757599>
> .
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by Kwpolska** [comment]
We would probably need to figure out how to remove that file from zipballs.
