### ISSUE TITLE
page broken in all jinja theme demos

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola-themes#75]
see

https://themes.getnikola.com/v7/bootstrap3-gradients-jinja/stories/dr-nikolas-vendetta.html
https://themes.getnikola.com/v7/base-jinja/stories/dr-nikolas-vendetta.html
https://themes.getnikola.com/v7/bootstrap3-jinja/stories/dr-nikolas-vendetta.html

**Comment by Kwpolska** [comment]
This is a bit hard to fix. We could, however, try to jinjify the template when we detect a jinja-based theme.

Or we could put the `book.tmpl` template in our base themes, but I don’t think that’s feasible…

**Comment by ralsina** [comment]
Yeah, book.tmpl is just too peculiar :-)

We could make the themes site jinjify templates/
