### ISSUE TITLE
Lanyon: Line numbers of code listing isn't formatted properly.

### ISSUE THREAD

**Issue by iAmMrinal0** [getnikola/nikola-themes#86]
As seen in the demo [here](https://themes.getnikola.com/v7/lanyon/listings/hello.py.html), the style breaks the line numbers resulting in poor formatting.

**Comment by iAmMrinal0** [comment]
I removed this line in [poole.css](https://github.com/getnikola/nikola-themes/blob/master/v7/lanyon/assets/css/poole.css#L170) and it fixes it, however when there's a lengthy string the text overflows and no scroll is shown.
![screenshot from 2016-06-27 03 21 30](https://cloud.githubusercontent.com/assets/890062/16365185/56ad8820-3c16-11e6-9d44-41070796de97.png)

Would require some help to figure this out.

**Comment by Kwpolska** [comment]
I’ll try to fix this.

**Comment by Kwpolska** [comment]
Fixed on the `lanyon-listing-overflow` branch — pending getnikola/nikola#2383.
