### ISSUE TITLE
zen theme: not playing well with https

### ISSUE THREAD

**Issue by dacoex** [getnikola/nikola-themes#90]
Example:
https://dacoex.github.io/

the icons of font awesome are not shown when https is used.

Solution from wiki:
https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

points to:
http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by Kwpolska** [comment]
This was fixed in commit c9039ee9 on February 29, 2016. Please reinstall your theme with `nikola theme -i`, rebuild and redeploy.
