### ISSUE TITLE
Responsive tables in Lanyon theme?

### ISSUE THREAD

**Issue by jcvanelst** [getnikola/nikola-themes#93]
Hi. I'm using the lanyon theme for Nikola (and love it for its UI friendliness and general responisivenees) but, when it comes to tables, have the same issue as descibed here : https://github.com/poole/lanyon/issues/62 .

Does mdo's reply automatically imply that a responsive table functionality will not be added in the Nikola-ready theme? I'd love to help out and help make it work, but this kind of stuff is sort of new for me. Found some basic examples here: http://codepen.io/anon/pen/BLdKrR or here: http://codepen.io/dbushell/full/8e6a1ee85418f3c5abe839647dbcdec5/ , but it seems quite a hassle to implement this in the broader scope of nikola....Any idea's, suggestions of what I could do to help out?

**Comment by Kwpolska** [comment]
If the original theme authors won’t bother, neither will we.

Feel free to make it work for your site, or to contribute a solution upstream.
